name: LegendHG
main: com.ronaldophc.LegendHG
version: 0.1.0-SNAPSHOT
author: RonaldoPHC
api-version: 1.8.8
load: POSTWORLD
softdepend: [ ProtocolLib ]
commands:
    maintenance:
    unban:
    ban:
    unmute:
    mute:
    unbanip:
    hour:
    banip:
    say:
    admin:
    vanish:
    build:
    rdc:
    lschematic:
    sound:
    gm:
    countdown:
        description: Command to set time of countdown
        usage: /countdown set <seconds>
        aliases: [ctd]
    invincibility:
        description: Command to control state invincibility
        usage: /invincibility <set:start> <seconds>
        aliases: [invi]
    invsee:
    kick:
    ping:
    report:
    reports:
    kit:
    kit2:
    pull:
        description: Command to pull player
        usage: /pull <player>
    flyspeed:
    lfeast:
    feast:
    minifeast:
    register:
        description: Register in the server
        usage: /register <password>
        aliases: [registrar, cadastrar]
    login:
        description: Login in the server
        usage: /login <password>
        aliases: [entrar]
    playerson:
        description: Command to see players online
        usage: /playerson
    scoreboard:
        description: Command to change scoreboard
        usage: /scoreboard
        aliases: [sb, score]
    skin:
        description: Command to change skin
        usage: /skin <skin>
        aliases: [changeskin, cs]
    crash:
        description: Command to crash player
        usage: /crash
    fake:
        description: Command to fake player
        usage: /fake <player>
    tag:
        description: Command to set tag
        usage: /tag <tag>
    ip:
        description: Command to see ip of player
        usage: /ip <player>
    prefs:
        description: Command to see preferences
        usage: /prefs
    staffchat:
        description: Command to talk in staff chat
        usage: /staffchat <message>
        aliases: [sc]
    tell:
        description: Command to send private message
        usage: /tell <player> <message>
        aliases: [msg, w, sussurro]
    teleport:
        description: Command to teleport
        usage: /teleport <player>
        aliases: [tp]
    stats:
        description: Command to see stats
        usage: /stats <player>
        aliases: [status]
    profile:
        description: See the profile
        usage: /profile
    kills:
        description: See the kills in this game
        usage: /kills