# LegendHG
# Ambiente de desenvolvimento(dev ou prod).
# No Dev desabilita o pré-load das chunks e gera alguns debugs.
Environment: dev
#
# Tempo para iniciar o HG após iniciar o servidor em segundos
Countdown: 120
#
# Tempo de invencibilidade em segundos
Invincibility: 120
#
# Tempo de jogo para spawnar o Feast em segungos
Feast: 120
#
# Minimo de jogadores para iniciar o HG
MinPlayers: 1
#
# Maximo de players no servidor
MaxPlayers: 50
#
#
# Database
Database:
  # Host: 'mysql' se for local(nome do container do MYSQL)
  Host: localhost
  Port: 3306
  User: sqluser
  Password: root
  Database: legendhg
#
# Modo de jogo - 1 = 1 Kit, 2 = 2 Kits, 3 = aleatório para cada partida.
Kits: 2
#
# Mensagens da lista de servidores
Msg1: "§b§lLegendMC§f§l >> §f§l1.7x 1.8x"
Msg2: "§a§lEm desenvolvimento!"